### ISSUE TITLE
Problem with Event Refund

### ISSUE THREAD

**Issue by Lumeriol** [AlexWestergaard/php-ga4#16]
In GA4 documentation there are two types of Refund - partial and full.
When I use event for Full refund, I need to set Items, but only transaction_id should be required. Items (selected) are required for partial refund.

**Comment by AlexWestergaard** [comment]
Thank you @Lumeriol for letting me know! I will have a look at it a bit later today.

**Comment by AlexWestergaard** [comment]
I have added a method `isFullRefund` parameter that will determine if `items` are required.

`Refund::new()->isFullRefund(true)->setTransactionId($id)`

**Comment by AlexWestergaard** [comment]
https://github.com/AlexWestergaard/php-ga4/releases/tag/v1.0.6
